### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by Ninja-FSE** [luadch/announcer_client#10]
Maybe an update to Announcer is needed so it supports the lastest version of Luadch or add TLSv1.3.

**Comment by bigbird-dk** [comment]
That Would be so great, if this could be done 🙌

**Comment by Sopor** [comment]
The Announcer won't work in Luadch 2.21, but it should work in 2.22 and higher, but not TLS v1.3.

I don't know when it will be done but it is added to the todo-list.

**Comment by bigbird-dk** [comment]
> The Announcer won't work in Luadch 2.21, but it should work in 2.22 and higher, but not TLS v1.3.
> 
> I don't know when it will be done but it is added to the todo-list.

I Would love that, been missing Announcer, since i upgraded to TLS1.3 🙏🙌

**Comment by Ninja-FSE** [comment]
> I Would love that, been missing Announcer, since i upgraded to TLS1.3 🙏🙌


Same here :)

Hoping for an update soon!

**Comment by Ninja-FSE** [comment]
fired up a test hub version 2.22 RC4 and TLSv1.2 getting this error now in the announcer log

> [2021-12-11/12:17:27] Connected. Try a SSL handshake...
> [2021-12-11/12:17:27] Generate keyprint...
> [2021-12-11/12:17:27] Connection with Keyprint verification...
> [2021-12-11/12:17:27] Connection established. Try now to login...
> [2021-12-11/12:17:27] Sending support...
> [2021-12-11/12:17:27] Waiting for hub support...
> [2021-12-11/12:17:27] Check for OSNR support...
> [2021-12-11/12:17:27] Hub has OSNR support, waiting for SID...
> [2021-12-11/12:17:27] Provided SID: D52X
> [2021-12-11/12:17:27] Waiting for hub INF...
> [2021-12-11/12:17:27] Hub INF provided, try to send own INF...
> [2021-12-11/12:17:27] Own INF sended, waiting for password request...
> [2021-12-11/12:17:27] Salt provided, try to send password...
> [2021-12-11/12:17:27] Waiting for login...
> [2021-12-11/12:17:27] Login failed. Last hub message: IINF NISHL DETestHub
> [2021-12-11/12:17:27] Bot terminated.
> 

I'm i doing something wrong? Or isnt the announcer working on RC4?

**Comment by Sopor** [comment]
My bad. It seems that is was not fixed until 2.23 RC1 or you can try 2.22 FINAL.

I suggest you to update to 2.23 RC9 if you want to run the Announcer and use TLS v1.2.

**Comment by Ninja-FSE** [comment]
> My bad. It seems that is was not fixed until 2.23 RC1 or you can try 2.22 FINAL.
> 
> I suggest you to update to 2.23 RC9 if you want to run the Announcer and use TLS v1.2.

Can confirm that the Announcer works on 2.23-RC9 with TLS v1.2.
