### ISSUE TITLE
Tab icons disappears after a while

### ISSUE THREAD

**Issue by Sopor** [luadch/announcer_client#15]
When starting the Announcer all the tab icons are visible, but after connecting to a hub and changing tabs they will disappear.

Before:
![image](https://user-images.githubusercontent.com/5789283/159853146-2afab712-88e5-4e57-acfd-48bff927de81.png)

After:
![image](https://user-images.githubusercontent.com/5789283/159852930-e5cbbdab-2b3d-4b9e-a4ca-81e747b3e9b3.png)

**Comment by pulsar-de** [comment]
fixed with: 2b00b0d15355cc506d9a20144a3a040ed12c003d
