### ISSUE TITLE
announcer_bot_v0.02 disconnect after 30 min of inactivity

### ISSUE THREAD

**Issue by technicianGF** [luadch/announcer_client#3]
hi,

I don't know why but my bot disconnect from the hub after 30 min of inactivity. As long as the bot has new stuff to announce, works well. But 30 min after last announce the bot disconnect from hub but continues to work, I then must close it and rerun it to join the hub. Tested the annoucer CLI on win and linux+wine to same ssl hub, same behaviour.

hub config
- debian 8.5 (iptables set for allowing hub port)
- luadch 2.18 
- ssl only + TLSv1.2 with AES128 + AES256 (default)

announcer config
- running on win 8.1 x64 or debian 8.5 x64 with x86 architecture
- tls v1.2
- permission level 55

I tried announce bots GUI, CLI
I tried to change, one by one, each parameters: cfg.botshare cfg.botslots cfg.announceinterval cfg.sockettimeout cfg.sleeptime
I tried using standard characters for bot name/description
I tried setting different permissions levels from 40 to 80
I tried to disable trafficmanager
All with no effect

> > > I enabled log_events, I can see this... Have an ssl handshake error
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': starting ssl handshake
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': error during ssl handshake: wantread
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapserver': accepted new client connection from 127.0.0.1:37941 to #HIDDEN#
> > > [2016-09-11 | 01:06:31] hub.lua: function 'newuser': sid of new user: 7DPL
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': error during ssl handshake: wantread
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': ssl handshake done
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': read data 'HSUP ADBASE ADTIGR ADOSNR ADKEYP ADADCS ADADC0', error: nil
> > > [2016-09-11 | 01:06:31] adc.lua: try to parse 'HSUP ADBASE ADTIGR ADOSNR ADKEYP ADADCS ADADC0'
> > > [2016-09-11 | 01:06:31] adc.lua: function 'parse': parsed 'HSUP ADBASE ADTIGR ADOSNR ADKEYP ADADCS ADADC0
> > > '
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': user: 7DPL, state: protocol
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': adc command processed
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': sended 'ISUP ADBAS0 ADBASE ADTIGR ADKEYP ADOSNR ADUCM0 ADUCMD
> > > ISID 7DPL
> > > IINF NI#HIDDEN# APLUADCH VEv2.18 DE#HIDDEN# HU1 HI1 CT32
> > > ', bytes: 167, error: nil, part: nil, to: 127.0.0.1:37941
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': read data 'BINF 7DPL VErelspam++ NI#HIDDEN# PDQ2Y4MK2CNKBIHWVXQJIY7P5PEGNJ6LJVDXL5TLA IDIC7ZT2UPJURM3TBO3BXBDIJAUZY5MQXYBTPE2EY HN0 HR0 HO0 SUOSNR,ADC0,ADCS SS268435456001 SL2 DE#HIDDEN#', error: nil
> > > [2016-09-11 | 01:06:31] adc.lua: try to parse 'BINF 7DPL VErelspam++ NI#HIDDEN# PDQ2Y4MK2CNKBIHWVXQJIY7P5PEGNJ6LJVDXL5TLA IDIC7ZT2UPJURM3TBO3BXBDIJAUZY5MQXYBTPE2EY HN0 HR0 HO0 SUOSNR,ADC0,ADCS SS268435456001 SL2 DE#HIDDEN#'
> > > [2016-09-11 | 01:06:31] adc.lua: function 'parse': parsed 'BINF 7DPL VErelspam++ NI#HIDDEN# PDQ2Y4MK2CNKBIHWVXQJIY7P5PEGNJ6LJVDXL5TLA IDIC7ZT2UPJURM3TBO3BXBDIJAUZY5MQXYBTPE2EY HN0 HR0 HO0 SUOSNR,ADC0,ADCS SS268435456001 SL2 DE#HIDDEN#
> > > '
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': user: 7DPL, state: identify
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': adc command processed
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': sended 'IGPA NH4FSJF3PX
> > > ', bytes: 16, error: nil, part: nil, to: 127.0.0.1:37941
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': read data 'HPAS IYPXHR27UNWOJP2Z6NMJXJC5WCP5FI4B6LAIZ6I', error: nil
> > > [2016-09-11 | 01:06:31] adc.lua: try to parse 'HPAS IYPXHR27UNWOJP2Z6NMJXJC5WCP5FI4B6LAIZ6I'
> > > [2016-09-11 | 01:06:31] adc.lua: function 'parse': parsed 'HPAS IYPXHR27UNWOJP2Z6NMJXJC5WCP5FI4B6LAIZ6I
> > > '
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': user: 7DPL, state: verify
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': adc command processed
> > > ............................
> > > ............................
> > > [2016-09-11 | 01:06:31] server.lua: function 'wrapconnection': read data 'BINF 7DPL HR1', error: nil
> > > [2016-09-11 | 01:06:31] adc.lua: try to parse 'BINF 7DPL HR1'
> > > [2016-09-11 | 01:06:31] adc.lua: function 'parse': parsed 'BINF 7DPL HR1
> > > '
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': user: 7DPL, state: normal
> > > [2016-09-11 | 01:06:31] hub.lua: function 'incoming': adc command processed
> > > 
> > > Last Announce
> > > [2016-09-11 | 01:33:36] server.lua: function 'wrapconnection': read data 'BMSG 7DPL !addrel#HIDDEN#', error: nil
> > > [2016-09-11 | 01:33:36] adc.lua: try to parse 'BMSG 7DPL !addrel#HIDDEN#'
> > > [2016-09-11 | 01:33:36] adc.lua: function 'parse': parsed 'BMSG 7DPL !addrel#HIDDEN#
> > > '
> > > [2016-09-11 | 01:33:36] hub.lua: function 'incoming': user: 7DPL, state: normal
> > > [2016-09-11 | 01:33:36] hub.lua: function 'incoming': adc command processed
> > > 
> > > After 30 min with no announce 
> > > [2016-09-11 | 02:04:09] server.lua: function 'wrapconnection': try to close client handler...
> > > [2016-09-11 | 02:04:09] hub.lua: function 'disconnect': remove user 7DPL 127.0.0.1:37941
> > > [2016-09-11 | 02:04:09] server.lua: function 'wrapconnection': closed client handler and removed socket from lists

Thanks for your help guys...

**Comment by blasti** [comment]
is this still an issue? the announcer bot/client in the latest version should send a keeping alive message.

**Comment by technicianGF** [comment]
Yes and no, still the same pb, but found a trick with crontab which works great.

So you can close this ticket, thanks.
