### ISSUE TITLE
mapped Network folders will not work

### ISSUE THREAD

**Issue by c0r4ir** [luadch/announcer_client#4]
**Hub Config:**
luadch-2.19-linux-x64
ssl only + TLSv1.2 with AES128 + AES256 (default)

**Luadch Announcer Client v0.8 Win32 GUI Config:**
Windows 10 Pro x64 (on VM)

FYI. Seems that networked directories will not work. Bot loads for a few seconds and then gets kicked off the hub server. Announcer Client log shows that it is `'searching in ' //NAS107411/Scene_PC_Games` forever. I changed the announcer path to a local one and it works `C:/Users/VMWIN10/Scene_PC_Games`.

**Comment by Sopor** [comment]
You are using UNC path. Have you tried to map the network drive?

![image](https://user-images.githubusercontent.com/5789283/38942230-8f96a7fe-432e-11e8-90cc-c2888973bef0.png)

Or you can only map `\\NAS107411` and you will then be able to use Z:/Scene_PC_Games in the Announcer.

**Comment by c0r4ir** [comment]
Sopor, your method worked flawlessly. Thank you very much for the answer.
