### ISSUE TITLE
can only login once ??

### ISSUE THREAD

**Issue by bigbird-dk** [luadch/announcer_client#5]
i set this client up, and i can login fine once!!, if i log off, and try to logon again, i comes up with this.
If i change username of the client, then i can login once again.
can anybody, help me with this issue ?
BTW, i'm using "Luadch_Announcer_Client_v0.8_Win32"

[2018-12-06/16:20:38] Announcer started. (process id: 5348)
[2018-12-06/16:20:38] Try to connect to hub...
[2018-12-06/16:20:41] Connected. Try a SSL handshake...
[2018-12-06/16:20:41] Generate keyprint...
[2018-12-06/16:20:41] Connection established. Try now to login...
[2018-12-06/16:20:41] Sending support...
[2018-12-06/16:20:42] Waiting for hub support...
[2018-12-06/16:20:42] Check for OSNR support...
[2018-12-06/16:20:42] Hub has OSNR support, waiting for SID...
[2018-12-06/16:20:42] Provided SID: 4CMT
[2018-12-06/16:20:42] Waiting for hub INF...
[2018-12-06/16:20:42] Hub INF provided, try to send own INF...
[2018-12-06/16:20:42] Own INF sended, waiting for password request...
[2018-12-06/16:20:42] Fail: No password request, closing...
[2018-12-06/16:20:42] No password request, closing...

**Comment by Sopor** [comment]
I'm running it without any issues and i have never heard of this.
What version of Luadch are you running and what OS?
Are you running the Announcer in a real Windows (not wine)?
Any error message in the log files (hubsoft)?
What level do the Announcer account have?

**Comment by bigbird-dk** [comment]
Luadch version 2.19, on a windows 7 pc
and the announcer on the same pc.
the announcer had level 60 rights, and i even set it up to owner (level 100)
to see it that was the problem.

after my first post in here, i closed the hub down, and started it again, and tried to login with the announcer client, that worked, but same problem when i logged off, and tried to login again.

i just looked into the error log, not any errors since i set the announcer up.

**Comment by Sopor** [comment]
And it is the same issue even if you restart the Announcer?
Do you connect with local IP address or domain/external IP address? I know there can be issues when running hubsoft and client behind the same router. I don't know if it will be in this case, though. Maybe you already have tried?

**Comment by bigbird-dk** [comment]
Yes, even if i restart announcer.
i’ve tried with 127.0.0.1 , 192.168.100.125 (local lan ip) , external ip, and the dns address.
can it be something wrong in settings in hubsoft, as if i close the hub down, and start it again i can connect once again

**Comment by Sopor** [comment]
And you have generated a unique certificate for the Announcer?
Did you use the [Luadch_Certmanager_v1.2_Win32](https://github.com/luadch/certmanager/releases)?

**Comment by bigbird-dk** [comment]
Yes, and put the generated certs in the cert folder in announcer dir

**Comment by Sopor** [comment]
You have no problems with regular accounts if a user log in and out?

Try do the same on a totally clean installation of Luadch and see if you get the same behavior. That will rule out the hubsoft settings.

You can even use the same cert for the hub. Only create a new folder and don't use the same port.

**Comment by bigbird-dk** [comment]
i started a new hub up, no problem with repeatedly logins. WORKED, :)

then i started to check what could be wrong, i came to that the "ptx_tophubbers.lua" script messed it up, 
i disabled that script now i can login again and again. Yeah!!

when the announcer program is running, does it announce check after those 300 seconds, and if there's new stuff then announces it ?

**Comment by Sopor** [comment]
Yes, it will search every 300 secs.

I believe you can close this issue now :)

**Comment by bigbird-dk** [comment]
thanks so much for the help :)
