### ISSUE TITLE
just a short question

### ISSUE THREAD

**Issue by bigbird-dk** [luadch/announcer_client#6]
now i got the announcer to work, (Yeah) 
i've now tried to get 2 announcers set up for det other hubowner, not same login nick, nor same certs, but when 1 login, the other is logged off, and vice versa.

is it possible ?

**Comment by Sopor** [comment]
Yes, you need to have two different accounts, but you can use the option `Use alternative nick` in the `Announcer rules` to add to the `freshstuff` in another name.
If you run two Announcer both need different usernames too. The same rules work for the Announcer as for a regular user account. Every username must be unique.

**Comment by bigbird-dk** [comment]
i already set it up that way.
Username: announcer, and add via my hubowner account, in announcer Rules
Username: announcer2, and add via the other hubowner account, in announcer Rules
even 2 different usergroups, as i tried to put 1 in moderator group and the other in hubowner group.

**Comment by Sopor** [comment]
The Announcer should have level 55. Are you using the same cert in both Announcer? The Announcer works the same way you are running two DC clients. So you must have made something wrong.

**Comment by bigbird-dk** [comment]
Ok, thank you, i’ll dig into this a bit more :)

**Comment by Sopor** [comment]
But why do you run two Announcers at the same user or do i misunderstand something?

**Comment by bigbird-dk** [comment]
yes you did, i run one, and the co-hubowner is going to run one also 👍.

but i’ll tinker around with it, thanks for the help sofar

**Comment by bigbird-dk** [comment]
got it working, started from scratch, and set uit up again, now it works with 2 accounts, tanks for your patience ;)
